parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''
    env(resolve:DATABASE_USER): ''

doctrine:
    dbal:
        # configure these for your database server
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_pgsql'
        server_version: '10.4'
        user: postgres
        password: ~
        charset: utf8
    orm:
        dql:
            string_functions:
                ts_match: 'Opsway\Doctrine\ORM\Query\AST\Functions\TsMatch'
                # json_string: 'App\DQL\JsonFunction'
            datetime_functions:
                date_trunc: 'App\Doctrine\DQL\DateTruncFunction'
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App