easy_admin:
  entities:
    Post:
      class: 'App\Entity\Post'
      label: post.entity_label
      list:
        actions: ['show']
        title: post.list_header
        fields:
          - { property: 'id', label: 'post.id' }
          - { property: 'title', label: 'post.title' }
          - { property: 'timeCreated', label: 'post.time_created' }
          - { property: 'timeModified', label: 'post.time_modified' }
      show:
        title: post.show_header
        fields:
          - { property: 'id', label: 'post.id' }
          - { property: 'title', label: 'post.title' }
          - { property: 'content', label: 'post.content' }
          - { property: 'tags', label: 'post.tags' }
          - { property: 'timeCreated', label: 'post.time_created' }
          - { property: 'timeModified', label: 'post.time_modified' }
      form:
        fields:
          - { property: 'title',  type_options: { required: true, label: 'post.title' } }
          - { property: 'content',  type_options: { required: true, label: 'post.content' } }
